src/utils/bedrock_agent_helper.py
*Issue #, if available:* Issue #6
*Description of changes:* removing extra allow line
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
=> issue #6 resolved

examples/multi-agent-collaboration/energy_efficiency_management_agent/4-energy-agent-collaborator/4.2_energy_agent_invocation.ipynb, examples/multi-agent-collaboration/mortgage_assistant/main.py, src/utils/knowledge_base_helper.py
*Issue #, if available:*
*Description of changes:*
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
=> fix: 🐛 fixing mortgage agent

examples/multi_agent_collaboration/mortgage_assistant/main.py
```
Changes to main.py., as to add in the new Agent greeting feature
```
issue#
* List the shared tools that your example is using: 
```
1. web_search
2. ...
```
```
2. ...
```
Changes to utils folder won't be accepted. Instead, open a new [issue](https://github.com/awslabs/amazon-bedrock-agent-samples/issues). 
* Business justification for including a new tool
```
```
* How is this tool implemented? 
=> Added greeting Agent feature

CONTRIBUTORS.md, RELEASE_NOTES.md, examples/agents/agent_with_models_not_yet_optimized_for_bedrock_agents/agent_llama.py, examples/agents/agent_with_models_not_yet_optimized_for_bedrock_agents/knowledge_base.py, examples/agents/agent_with_models_not_yet_optimized_for_bedrock_agents/lambda_function.py, examples/agents/agent_with_models_not_yet_optimized_for_bedrock_agents/restaurant_booking_llama_agent.ipynb
<hr/>
Added a code sample for not yet optimized models for Llama
```
```
<hr/>
<hr/>
* [y] Have you followed the guidelines in our Contributing document?
* [y] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/awslabs/amazon-bedrock-agent-samples/pulls) for the same update/change?
* [n ] Are you uploading a dataset?
* [y] Have you added contributions to [RELEASE NOTES](/RELEASE_NOTES.md)?
<hr/>
* [ y] Have you tested your code, and made sure the functionality …
=> added llama code sample

CONTRIBUTORS.md, examples/agents/video_games_sales_assistant_with_amazon_bedrock_agents/README.md, examples/agents/video_games_sales_assistant_with_amazon_bedrock_agents/amplify-video-games-sales-assistant-sample/README.md, examples/agents/video_games_sales_assistant_with_amazon_bedrock_agents/sam-bedrock-video-games-sales-assistant/README.md, examples/agents/video_games_sales_assistant_with_amazon_bedrock_agents/sam-bedrock-video-games-sales-assistant/manual_database_data_load_and_agent_creation.md
Wording update, license and contributor.
=> Data analyst assistant

src/utils/bedrock_agent_helper.py, src/utils/knowledge_base_helper.py
<hr/>
```
Fix delete_kb() in bedrock_agent_helper() to print notification and succeed if KB does not exist, not throw exception
```
<hr/>
<hr/>
<hr/>
```
1. web_search
2. ...
```
```
1. knowledge_base_helper.py
```
<hr/>
<hr/>
```
This tool is …
```
=> Fix bug44 - delete_kb() in bedrock_agent_helper() throws exception if KB does not exist

src/utils/bedrock_agent_helper.py
<hr/>
```
Improved formatting to event stream output in bedrock_agents_helper
```
<hr/>
<hr/>
<hr/>
```
1. web_search
2. ...
```
```
2. ...
```
<hr/>
<hr/>
```
```
* How is this tool …
=> Added Mark Roy's improved formatting to bedrock_agent_helper and tested

examples/multi_agent_collaboration/support_agent/README.md, examples/multi_agent_collaboration/support_agent/knowledge_base_webcrawler_helper.py, examples/multi_agent_collaboration/support_agent/main.py
<hr/>
* [x ] Concise description of the PR
```
Changes to main.py and knowledge_base_webcrawler_helper.py file to fix some bugs
```
<hr/>
<hr/>
* [x ] Have you followed the guidelines in our Contributing document?
* [x ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/awslabs/amazon-bedrock-agent-samples/pulls) for the same update/change?
* [ x] Have you added contributions to [RELEASE NOTES](/RELEASE_NOTES.md)?
<hr/>
* [x ] Have you tested your code, and made sure the functionality …
=> [bugs] Support agent fix

examples/agents_ux/inline-agent-hr-assistant/templates/index.html
<hr/>
```
```
<hr/>
<hr/>
<hr/>
```
1. web_search
2. ...
```
```
2. ...
```
<hr/>
<hr/>
```
```
- * [ ] AWS …
=> removed login and adding a simpler selection index.html file

src/shared/economic_data/README.md, src/shared/property_data/README.md, src/utils/bedrock_agent_helper.py
<hr/>
```
```
<hr/>
<hr/>
<hr/>
```
1. web_search
2. ...
```
```
2. ...
```
<hr/>
<hr/>
```
```
- * [ ] AWS …
=> Disclaimer Added for Property tool

examples/agents/computer_use/README.md, examples/agents/computer_use/makefile
<hr/>
```
```
<hr/>
<hr/>
<hr/>
```
1. web_search
2. ...
```
```
2. ...
```
<hr/>
<hr/>
```
```
- * [ ] AWS …
=> Computer use phony

src/InlineAgent/src/InlineAgent/tools/mcp.py
<hr/>
```
After analyzing the code, I've identified the issue with the Inline agent passing only the last tool name to the MCP server.
The Issue
The issue is in the set_callable_tool method in the MCPServer class. When creating callable functions for each tool, the method is using a closure that 
captures the tool.name variable in a loop, but due to how Python closures work, all the functions end up referencing the last value of tool.name in the 
loop.
I implemented a factory function pattern that creates a new function …
```
=> fix: Agent only calls last tool name

src/InlineAgent/README.md
<hr/>
Fix the wrong url typo on mcp example.
```
```
<hr/>
<hr/>
<hr/>
**Not applicable**
* [] Have you tested your code, and made sure the functionality runs successfully? Provide screenshots. 
* [] Have you linted your Python code with [black](https://github.com/psf/black)?
* [] Does this implementation use the shared tools `src/utils/*`. List them here:
```
1. web_search
2. ...
```
**Not applicable**
```
2. ...
```
**Not applicable**
<hr/>
Changes to the utils …
=> Fix the wrong url typo on mcp example.

src/InlineAgent/examples/mcp/cost_explorer_agent/README.md
<hr/>
```
Replaced the link to https://github.com/aarora79/aws-cost-explorer-mcp-server with https://github.com/aws-samples/sample-cloud-spend-mcp-server in https://github.com/aarora79/amazon-bedrock-agent-samples/blob/main/src/InlineAgent/examples/mcp/cost_explorer_agent/README.md
```
<hr/>
<hr/>
<hr/>
```
1. web_search
2. ...
```
```
2. ...
```
<hr/>
<hr/> …
=> Fix repo name for cost explorer MCP server

examples/multi_agent_collaboration/investment_research_agent/README.md, examples/multi_agent_collaboration/investment_research_agent/main.ipynb
<hr/>
```
```
<hr/>
<hr/>
<hr/>
```
1. web_search
2. ...
```
```
2. ...
```
<hr/>
<hr/>
```
```
- * [ ] AWS …
=> InvestmentResearchAgent - Update

examples/agents/human_in_the_loop/cdk/README.md
<hr/>
```
Fix broken picture link, for some reason this is the only one in jpg format in the pictures folder: https://github.com/awslabs/amazon-bedrock-agent-samples/blob/main/examples/agents/human_in_the_loop/images/console-add-confirmation.jpg
```
<hr/>
<hr/>
<hr/>
```
```
```
```
<hr/>
<hr/>
Changes to existing tools won't be accepted. Instead, open a new …
=> fix: action confirmation picture link was broken

examples/multi_agent_collaboration/support_agent/knowledge_base_confluence_helper.py
<hr/>
```
Changes to Confluence region., because there waas a bug rasied that the region is strict to us-west-2 and it should be depending on where the code is running
```
<hr/>
* [ https://github.com/awslabs/amazon-bedrock-agent-samples/issues/68] Issue # (if applicable)
<hr/>
* [ x] Have you followed the guidelines in our Contributing document?
* [ x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/awslabs/amazon-bedrock-agent-samples/pulls) for the same update/change?
<hr/>
* [x ] …
=> Fixing region bug

examples/agents_ux/foursquare_location/README.md
<hr/>
```
```
<hr/>
<hr/>
<hr/>
```
1. web_search
2. ...
```
```
2. ...
```
<hr/>
<hr/>
```
```
- * [ ] AWS …
=> Add instructions on how to obtain the Foursquare API key.

src/InlineAgent/examples/mcp/aws_cloud_guard_mcp/.env.example, src/InlineAgent/examples/mcp/aws_cloud_guard_mcp/README.md, src/InlineAgent/examples/mcp/aws_cloud_guard_mcp/config.py, src/InlineAgent/examples/mcp/aws_cloud_guard_mcp/main.py
<hr/>
```
This PR contains the MCP implementation of AWS cloudguard using bedrock inline agents: View the original repository here: https://github.com/madhurprash/AWS_CloudGuardMCP
```
<hr/>
<hr/>
<hr/>
```
1. The code works and is fully tested
```
```
```
<hr/>
<hr/>
Changes to existing tools won't be accepted. Instead, open a new …
=> Adding AWS cloud guard as an MCP example to inline agents

src/InlineAgent/src/InlineAgent/hello_world.py
The hello_world.py for Inlineagent currently hardcodes the claude haiku model when it prints out the code, even if the user specifies a different model. 
```
(.venv) ➜  InlineAgent git:(main) InlineAgent_hello us.deepseek.r1-v1:0                     
Running Hellow world agent:                                                                                                                                   
from bedrock_agents.agent import InlineAgent                                                                                                                 
InlineAgent(                                                                                                                                                 
foundationModel="us.anthropic.claude-3-5-haiku-20241022-v1:0", …
```
=> Use model id that user specifies in the printed code
